track = {
  "abandoned boardwalk": 170,
  "abyssal ruins": 201,
  "alpine peak": 59,
  "aquadrom stage": 200,
  "aquania": 169,
  "asdf course": 77,
  "athletic raceway": 183,
  "aura metropolis": 167,
  "autumn leavesway": 146,
  "big express city": 36,
  "big nature city": 244,
  "boshi skatepark": 219,
  "bowser's fiery fortress": 228,
  "calidae desert": 160,
  "camp kartigan": 182,
  "candy coaster": 121,
  "canyon run": 125,
  "castle of darkness": 155,
  "castle of time": 250,
  "cave island": 151,
  "celestial ruins": 44,
  "cherry blossom garden": 204,
  "christmas court": 197,
  "coin heaven": 162,
  "colour circuit": 39,
  "colour wonderland": 50,
  "comet starway": 239,
  "concord town": 35,
  "crystal dungeon": 206,
  "crystal plains": 198,
  "ctr blizzard bluff": 168,
  "ctr cortex castle": 141,
  "ctr n. gin labs": 216,
  "daisy hillside": 60,
  "daisy's palace": 42,
  "dark matter fortress": 211,
  "dark matter shrine": 133,
  "dawn township": 111,
  "delfino island": 110,
  "desert castle raceway": 156,
  "desert fort": 78,
  "desert mushroom ruins": 172,
  "desktop dash": 165,
  "dk ruins": 189,
  "dkr star city": 85,
  "dragon burial grounds": 190,
  "dragonite's island": 247,
  "dreamworld cloudway": 191,
  "ds airship fortress": 91,
  "ds bowser castle": 40,
  "ds cheep cheep beach": 119,
  "ds dk pass": 194,
  "ds figure-8 circuit": 115,
  "ds luigi's mansion": 147,
  "ds mario circuit": 153,
  "ds shroom ridge": 41,
  "ds tick-tock clock": 135,
  "ds waluigi pinball": 102,
  "ds wario stadium": 117,
  "envenom snowstorm": 138,
  "festival town": 243,
  "final grounds": 123,
  "fishdom island": 87,
  "flowery greenhouse": 51,
  "flying kingdom": 74,
  "forest creek": 202,
  "fungal jungle": 231,
  "garden of dreams": 134,
  "gba bowser castle 1": 166,
  "gba bowser castle 2": 233,
  "gba bowser castle 4": 101,
  "gba broken pier": 105,
  "gba cheep cheep island": 112,
  "gba cheese land": 145,
  "gba lakeside park": 185,
  "gba luigi circuit": 184,
  "gba mario circuit": 187,
  "gba peach circuit": 43,
  "gba rainbow road": 48,
  "gba ribbon road": 152,
  "gba riverside park": 33,
  "gba sky garden": 149,
  "gba snow land": 212,
  "gba sunset wilds": 46,
  "gcn baby park": 164,
  "gcn bowser's castle": 100,
  "gcn daisy cruiser": 116,
  "gcn dry dry desert": 32,
  "gcn luigi circuit": 129,
  "gcn mushroom bridge": 213,
  "gcn mushroom city": 173,
  "gcn rainbow road": 88,
  "gcn sherbet land": 139,
  "gcn wario colosseum": 132,
  "gcn yoshi circuit": 106,
  "glimmer express trains": 143,
  "gothic castle": 181,
  "gp mario beach": 224,
  "halogen highway": 49,
  "haunted gardens": 84,
  "headlong skyway": 238,
  "heart of china": 253,
  "hellado mountain": 177,
  "honeybee hideout": 69,
  "icepeak mountain": 227,
  "incendia castle": 81,
  "infernal pipeyard": 144,
  "item fireland": 52,
  "jiyuu village": 248,
  "jungle cliff": 95,
  "jungle glade": 232,
  "jungle jamble": 220,
  "jungle ruins": 140,
  "kartwood creek": 86,
  "kinoko cave": 163,
  "koopa shell pipeland": 254,
  "lava lake": 175,
  "lava road": 218,
  "lost fortress": 37,
  "luigi's island": 222,
  "lunar lights": 93,
  "lunar spaceway": 221,
  "luncheon tour": 108,
  "magmatic sanctuary": 240,
  "mansion of madness": 234,
  "marble towers": 252,
  "mario castle raceway": 73,
  "medieval castlegrounds": 217,
  "melody sanctum": 148,
  "melting magma melee": 122,
  "misty ruins": 157,
  "mushroom island": 186,
  "mushroom peaks": 64,
  "mushroom valley": 38,
  "musical cliff": 154,
  "n64 banshee boardwalk": 104,
  "n64 choco mountain": 103,
  "n64 frappe snowland": 192,
  "n64 kalimari desert": 161,
  "n64 koopa troopa beach": 179,
  "n64 luigi raceway": 47,
  "n64 rainbow road": 57,
  "n64 royal raceway": 89,
  "n64 toad's turnpike": 226,
  "n64 wario stadium": 225,
  "neo koopa city": 136,
  "new moon manor": 126,
  "nightlife party": 96,
  "nivurbia": 150,
  "pianta shore": 61,
  "pinewood path": 63,
  "pipe underworld": 124,
  "piranha plant pipeline": 174,
  "quaking mad cliffs": 109,
  "rainbow road: solar edition": 249,
  "rezway": 171,
  "rock rock ridge": 53,
  "rosalina's snow world": 72,
  "rush city run": 79,
  "sadx twinkle circuit": 230,
  "sahara hideout": 237,
  "sakura sanctuary": 76,
  "sarasa kingdom": 80,
  "sea stadium": 159,
  "shy guy's market": 45,
  "siberian chateau": 34,
  "sinister vault": 208,
  "six king labyrinth": 92,
  "sky grove": 205,
  "sky high island": 215,
  "sky shrine": 75,
  "skyline avenue": 99,
  "slot circuit": 210,
  "snes bowser castle 1": 236,
  "snes bowser castle 2": 68,
  "snes bowser castle 3": 223,
  "snes choco island 2": 113,
  "snes donut plains 2": 94,
  "snes donut plains 3": 131,
  "snes ghost valley 1": 242,
  "snes koopa beach 2": 245,
  "snes mario circuit 1": 71,
  "snes mario circuit 2": 120,
  "snes rainbow road": 137,
  "spectral station": 90,
  "spike desert": 128,
  "star slope": 54,
  "stargaze summit": 158,
  "summer starville": 107,
  "sunset forest": 82,
  "sunset ridge": 178,
  "super marine world": 235,
  "superstar dystopia": 118,
  "suzuka circuit": 193,
  "the rabbit hole": 83,
  "thump bump forest": 199,
  "thwomp swamp": 251,
  "toad raceway": 127,
  "tropical factory": 207,
  "twin peaks": 114,
  "underground sky": 196,
  "undiscovered offlimit": 97,
  "unfinished mario circuit": 180,
  "unnamed valley": 130,
  "vile isle": 214,
  "volcanic valley": 195,
  "volcano canyon": 65,
  "waluigi's motocross": 70,
  "warp pipe island": 188,
  "wetland woods": 209,
  "white garden": 246,
  "windmill village": 203,
  "windy whirl": 229,
  "wolf castlegrounds": 142,
  "wuhu island": 62,
  "wuhu mountain": 176,
  "yoshi lagoon": 98,
  "yoshi's woolly raceway": 241
}

f = open("tracks.txt", "r+")
header=[67, 85, 80, 50, 0, 0, 0]
course_val=[]

tracks = f.read().split("\n")

for item in tracks:
    item = item.lower()
    loop = True
    while loop:
        if item in track:
            course_val.append(track[item])
            loop = False
        elif item not in track:
            item= input(item+" is not in my dictionary. Can you double check the spelling and try reentering below.\n")
            if item in track:
                course_val.append(track[item])
            loop = False
    else:
        loop = True

if len(tracks) % 4 != 0:
    x = len(tracks) % 4
    for i in range(1, x+1):
        course_val.append(course_val[-1])

cup = len(course_val) // 4
header.append(cup)

while len(course_val) <216:
    course_val.append(255)

f = open("cuplayout.cup", "w+b")
f.seek(0x00)
f.write(bytes(header))
f.seek(0x08)
f.write(bytes(course_val))
f.close()